package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

const resetDirective = "generate:reset"

type resetStruct struct {
	name string
}

func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}

	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}

func loadPackages(root string) ([]*packages.Package, error) {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax |
			packages.NeedTypes | packages.NeedTypesInfo | packages.NeedModule,
		Dir:  root,
		Fset: token.NewFileSet(),
	}

	return packages.Load(cfg, "./...")
}

func findResetStructs(pkg *packages.Package) []resetStruct {
	seen := make(map[string]struct{})
	var result []resetStruct

	for _, file := range pkg.Syntax {
		if strings.HasSuffix(pkg.Fset.Position(file.Pos()).Filename, "_test.go") {
			continue
		}

		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok || structType == nil {
					continue
				}

				if !hasResetDirective(genDecl.Doc, typeSpec.Doc, typeSpec.Comment) {
					continue
				}

				name := typeSpec.Name.Name
				if _, exists := seen[name]; exists {
					continue
				}
				seen[name] = struct{}{}
				result = append(result, resetStruct{name: name})
			}
		}
	}

	return result
}

func hasResetDirective(docs ...*ast.CommentGroup) bool {
	for _, doc := range docs {
		if doc == nil {
			continue
		}
		for _, comment := range doc.List {
			text := strings.TrimSpace(strings.TrimPrefix(comment.Text, "//"))
			if text == resetDirective {
				return true
			}
		}
	}
	return false
}

func generatePackage(pkg *packages.Package, structs []resetStruct) error {
	if len(structs) == 0 {
		return nil
	}

	dir := filepath.Dir(pkg.GoFiles[0])
	outPath := filepath.Join(dir, "reset.gen.go")

	var buf bytes.Buffer
	buf.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n\n")
	buf.WriteString(fmt.Sprintf("package %s\n\n", pkg.Name))

	resetTypes := make(map[string]struct{}, len(structs))
	for _, s := range structs {
		resetTypes[s.name] = struct{}{}
	}

	gen := &resetGenerator{
		pkg:        pkg.Types,
		resetTypes: resetTypes,
	}

	for _, s := range structs {
		obj := pkg.Types.Scope().Lookup(s.name)
		if obj == nil {
			return fmt.Errorf("package %s: type %s not found", pkg.PkgPath, s.name)
		}

		typeName, ok := obj.(*types.TypeName)
		if !ok {
			return fmt.Errorf("package %s: %s is not a type", pkg.PkgPath, s.name)
		}

		named, ok := typeName.Type().(*types.Named)
		if !ok {
			return fmt.Errorf("package %s: %s is not a named type", pkg.PkgPath, s.name)
		}

		structType, ok := named.Underlying().(*types.Struct)
		if !ok {
			return fmt.Errorf("package %s: %s is not a struct", pkg.PkgPath, s.name)
		}

		buf.WriteString(gen.method(s.name, structType))
		buf.WriteByte('\n')
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format generated code for %s: %w", pkg.PkgPath, err)
	}

	return os.WriteFile(outPath, formatted, 0o644)
}

type resetGenerator struct {
	pkg        *types.Package
	resetTypes map[string]struct{}
}

func (g *resetGenerator) method(structName string, structType *types.Struct) string {
	var body strings.Builder
	body.WriteString(fmt.Sprintf("func (s *%s) Reset() {\n", structName))
	body.WriteString("\tif s == nil {\n")
	body.WriteString("\t\treturn\n")
	body.WriteString("\t}\n\n")

	for i := 0; i < structType.NumFields(); i++ {
		field := structType.Field(i)
		expr := "s." + field.Name()
		for _, line := range g.resetLines(expr, field.Type()) {
			body.WriteString("\t" + line + "\n")
		}
	}

	body.WriteString("}\n")
	return body.String()
}

func (g *resetGenerator) resetLines(expr string, typ types.Type) []string {
	typ = types.Unalias(typ)

	switch t := typ.(type) {
	case *types.Basic:
		return []string{fmt.Sprintf("%s = %s", expr, basicZero(t))}
	case *types.Slice:
		return []string{fmt.Sprintf("%s = %s[:0]", expr, expr)}
	case *types.Map:
		return []string{fmt.Sprintf("clear(%s)", expr)}
	case *types.Pointer:
		if g.shouldCallReset(t.Elem()) {
			return []string{
				fmt.Sprintf("if resetter, ok := %s.(interface{ Reset() }); ok && %s != nil {", expr, expr),
				"\tresetter.Reset()",
				"}",
			}
		}

		lines := []string{fmt.Sprintf("if %s != nil {", expr)}
		lines = append(lines, indent(g.resetLines("*"+expr, t.Elem()))...)
		lines = append(lines, "}")
		return lines
	case *types.Struct:
		if g.shouldCallReset(t) {
			return []string{expr + ".Reset()"}
		}
		return []string{fmt.Sprintf("%s = %s", expr, zeroExpr(t, g.pkg))}
	case *types.Named:
		if g.shouldCallReset(t) {
			return []string{expr + ".Reset()"}
		}
		return g.resetLines(expr, t.Underlying())
	case *types.Interface:
		return []string{fmt.Sprintf("%s = nil", expr)}
	case *types.Chan:
		return []string{fmt.Sprintf("%s = nil", expr)}
	case *types.Array:
		return []string{fmt.Sprintf("%s = %s", expr, zeroExpr(t, g.pkg))}
	case *types.Signature:
		return []string{fmt.Sprintf("%s = nil", expr)}
	default:
		return []string{fmt.Sprintf("%s = %s", expr, zeroExpr(t, g.pkg))}
	}
}

func indent(lines []string) []string {
	prefix := strings.Repeat("\t", 1)
	result := make([]string, len(lines))
	for i, line := range lines {
		result[i] = prefix + line
	}
	return result
}

func (g *resetGenerator) shouldCallReset(typ types.Type) bool {
	typ = types.Unalias(typ)

	if named, ok := typ.(*types.Named); ok {
		if _, marked := g.resetTypes[named.Obj().Name()]; marked {
			return true
		}
	}

	return hasResetMethod(typ)
}

func hasResetMethod(typ types.Type) bool {
	typ = types.Unalias(typ)

	candidates := []types.Type{typ}
	if _, ok := typ.(*types.Pointer); !ok {
		candidates = append(candidates, types.NewPointer(typ))
	}

	for _, candidate := range candidates {
		mset := types.NewMethodSet(candidate)
		for i := 0; i < mset.Len(); i++ {
			sel := mset.At(i)
			if sel.Obj().Name() != "Reset" {
				continue
			}

			sig, ok := sel.Obj().Type().(*types.Signature)
			if ok && sig.Params().Len() == 0 && sig.Results().Len() == 0 {
				return true
			}
		}
	}

	return false
}

func basicZero(t *types.Basic) string {
	switch {
	case t.Info()&types.IsBoolean != 0:
		return "false"
	case t.Info()&types.IsString != 0:
		return `""`
	case t.Info()&types.IsComplex != 0:
		return "0"
	default:
		return "0"
	}
}

func zeroExpr(t types.Type, pkg *types.Package) string {
	t = types.Unalias(t)

	switch u := t.(type) {
	case *types.Basic:
		return basicZero(u)
	case *types.Pointer, *types.Interface, *types.Chan, *types.Signature:
		return "nil"
	case *types.Slice:
		return "nil"
	case *types.Map:
		return "nil"
	case *types.Array:
		return fmt.Sprintf("%s{}", typeString(u, pkg))
	case *types.Struct:
		return fmt.Sprintf("%s{}", typeString(u, pkg))
	case *types.Named:
		return fmt.Sprintf("%s{}", typeString(u, pkg))
	default:
		return fmt.Sprintf("%s{}", typeString(u, pkg))
	}
}

func typeString(t types.Type, pkg *types.Package) string {
	return types.TypeString(types.Unalias(t), func(p *types.Package) string {
		if p == nil || p == pkg {
			return ""
		}
		return p.Name()
	})
}
